/mob/character/build_intrinsics()
	. = ..()
	// register core resources
	register_resource(/datum/character_resource/health)
	register_resource(/datum/character_resource/mana)
	register_resource(/datum/character_resource/stamina)
	// register core stats
	register_stat(/datum/character_roll/character_stat/strength)
	register_stat(/datum/character_roll/character_stat/dexterity)
	register_stat(/datum/character_roll/character_stat/constitution)
	register_stat(/datum/character_roll/character_stat/intelligence)
	register_stat(/datum/character_roll/character_stat/wisdom)
	register_stat(/datum/character_roll/character_stat/charisma)
	// register skills
	register_skill(/datum/character_roll/character_skill/acrobatics)
	register_skill(/datum/character_roll/character_skill/athletics)
	register_skill(/datum/character_roll/character_skill/archaeology)
	register_skill(/datum/character_roll/character_skill/deception)
	register_skill(/datum/character_roll/character_skill/dungeoneering)
	register_skill(/datum/character_roll/character_skill/enchantment)
	register_skill(/datum/character_roll/character_skill/magitek)
	register_skill(/datum/character_roll/character_skill/medicine)
	register_skill(/datum/character_roll/character_skill/magic)
	register_skill(/datum/character_roll/character_skill/naturalist)
	register_skill(/datum/character_roll/character_skill/perception)
	register_skill(/datum/character_roll/character_skill/persuasion)
	register_skill(/datum/character_roll/character_skill/thievery)
	register_skill(/datum/character_roll/character_skill/survival)
	register_skill(/datum/character_roll/character_skill/investigation)
	register_skill(/datum/character_roll/character_skill/insight)
	register_skill(/datum/character_roll/character_skill/stealth)
