#define isAlist(value) istype(value, /alist)
#define isAppearance(value) istype(value, /mutable_appearance)
#define isArea(value) isarea(value)
#define isAtom(value) istype(value, /atom)
#define isClient(value) istype(value, /client)
#define isDatabase(value) istype(value, /database)
#define isDatum(value) istype(value, /datum)
#define isIcon(value) isicon(value)
#define isImage(value) istype(value, /image)
#define isList(value) islist(value)
#define isMatrix(value) istype(value, /matrix)
#define isMob(value) ismob(value)
#define isMovable(value) istype(value, /atom/movable)
#define isObj(value) isobj(value)
#define isPath(value) ispath(value)
#define isPixloc(value) istype(value, /pixloc)
#define isQuery(value) istype(value, /database/query)
#define isRegex(value) istype(value, /regex)
#define isSavefile(value) istype(savefile, /savefile)
#define isSound(value) istype(value, /sound)
#define isTurf(value) isturf(value)
#define isType(value, type) istype(value, type)
#define isVector(value) istype(vector, /vector)
