#define isNum(value) (isnum(value))
#define isNumber(value) (isnum(value))
#define isTruthyNumber(value) (isnum(value) && ((value) > 0))
#define isZeroNumber(value) (isnum(value) && ((value) == 0))
#define isFalsyNumber(value) (isnum(value) && ((value) == 0))
#define isNonZeroNumber(value) (isnum(value) && ((value) != 0))
#define isPositiveNumber(value) (isnum(value) && ((value) >= 0))
#define isNegativeNumber(value) (isnum(value) && ((value) < 0))
#define isInf(value) (isinf(value))
#define isInfNumber(value) (isinf(value))
#define hasDecimals(value) (isnum(value) && (((value) % 1) != 0))
#define isText(value) (istext(value))
#define isNonEmptyText(value) (istext(value) && (length(value) > 0))
#define hasMinCharacters(value, min) (istext(value) && isnum(min) && ((min) >= 0) && (length(value) >= (min)))
#define hasMaxCharacters(value, max) (istext(value) && isnum(max) && ((max) >= 0) && (length(value) <= (max)))
#define isNonEmptyList(value) (islist(value) && ((value:len) > 0))

proc
	hasMinDecimalSpaces(value, min = 1)
		var/regex/regex = regex(@"\d.+\.(\d.+)").Find("[value]")
		return hasDecimals(value) && hasMinCharacters(regex.match, min)